### ISSUE TITLE
accented letters make errors

### ISSUE THREAD

**Issue by francoisromain** [streetsidesoftware/vscode-cspell-dict-extensions#12]
Hello and thank you for this useful extension. 

I installed the french dictionnary and set `"cSpell.language": "en,fr"` in the preferences. 

It works fine but creates an error when a character is not accentuated in a french word. for exemple: `prénom` does not make an error, but `prenom` does. This is a good thing for a regular dictionnary, but not for code. In code, it is a common thing to use french words without accents. 

Is there a way to fix that? 

thank you

**Comment by Mangatt** [comment]
I agree, this is cumberstone for multiple languages. It would be great to have option to accept words without accents.

**Comment by Jason3S** [comment]
Support for this is currently in progress.

**Comment by maiconsaraiva** [comment]
In Brazilial Portuguese we have this problem too. Waiting for update to support non-acentued words, thank you.

**Comment by robertotcestari** [comment]
Was this solved?

**Comment by Jason3S** [comment]
It is currently in progress.

**Comment by izacsc** [comment]
Any updates on this?

**Comment by miquelbonastredreivip** [comment]
From @Jason3S list, point number 1 seems fixed in alpha version:

https://github.com/streetsidesoftware/vscode-spell-checker/pull/942
https://github.com/streetsidesoftware/vscode-spell-checker/commit/e4c2479a5e34430c597b5b076bea70a95ee9729d

So it follows that:

- It needs to mature and reach vscode marketplace
- Dictionaries need to be updated

👍

**Comment by Jason3S** [comment]
I'm slowing rebuilding the dictionaries.

Done so far:
- pt_BR
- ru
- de_DE
- sv_SE
- es_ES

Up next are French and Dutch.

Are there any preferences?

**Comment by natenho** [comment]
It would be a nice feature, I've just give up using pt_BR dictionary because of this, @Jason3S is it possible to release the dictionaries that are ready to go and build the remaining in new issues (e.g. per dictionary)?

**Comment by Jason3S** [comment]
@natenho,

They have already been released. See [Spell check ignore accentuation. · Issue #1060 · streetsidesoftware/cspell](https://github.com/streetsidesoftware/cspell/issues/1060#issuecomment-1007283031)

**Comment by natenho** [comment]
@Jason3S

I tried to use the settings described and I could not get it working...here is the json settings:

```
 "cSpell.language": "en,pt-BR",
    "cSpell.languageSettings": [
        {
            "locale": "pt",
            "languageId": "*",
            "caseSensitive": false,
        },
        {
            "locale": "pt",
            "languageId": [
                "markdown",
                "json",
                "yaml"
            ],
            "caseSensitive": true
        }
    ]
```

But the accented 

![image](https://user-images.githubusercontent.com/4236481/159012699-771add01-8a46-488c-962b-63b4d210b51f.png)

**Comment by Jason3S** [comment]
@natenho,

The `locale`s have to be the same or it won't match. `pt` is not the same as `pt-BR`.

If you set `locale` to be `pt,pt-BR`, it mean match against either `pt` or `pt-BR`.

Please try:

```json
    "cSpell.languageSettings": [
        {
            "locale": "pt,pt-BR",
            "languageId": "*",
            "caseSensitive": false,
        },
        {
            "locale": "pt,pt-BR",
            "languageId": [
                "markdown",
                "json",
                "yaml"
            ],
            "caseSensitive": true
        }
    ]
```

**Comment by natenho** [comment]
ok, now it works! thank you very much!!

I thought locale was a "contains" match, like stated in your [post here](https://github.com/streetsidesoftware/cspell/issues/1060#issuecomment-1007283031):

![image](https://user-images.githubusercontent.com/4236481/159017409-80bfa670-d9fb-47bc-8c66-3e27524aa1ab.png)

**Comment by Jason3S** [comment]
I can see how that is misleading.

**Comment by EwenQuim** [comment]
> Up next are French and Dutch.

Can you please add the french version? This extension seems really great but is currently unusable in French because of the amount of accented words. Thank you for your work!

**Comment by Jason3S** [comment]
@EwenQuim,

Thank you for the reminder. It has been published.

**Comment by Jason3S** [comment]
I'm closing this since nearly all dictionaries support this.
