### ISSUE TITLE
Publish Estonian

### ISSUE THREAD

**Issue by Jason3S** [streetsidesoftware/vscode-cspell-dict-extensions#165]
This issue is to keep track of the things that need to be done to publish the Estonian extension.

1. Add sample files.
2. Test extension
3. Publish

**Comment by igor-krupenja** [comment]
I can assist you with a sample and testing. Should I simply create a PR with a sample, similarly to [the PR that added Norwegian](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/commit/e57ea9270d2a3e0dc0d3da72328070ce0fb95ab7#diff-e78311d747bfcd7f32831d6b8eb942369477296a7abae8e348028dc8889440a6R1)? I was also thinking about the intro from [article on Estonia in Estonian Wikipedia](https://et.wikipedia.org/wiki/Eesti) but it's rather short and the longest paragraph is simply a collection of dates and names of international organisations. Maybe [first few paragraphs from History section of the same article](https://et.wikipedia.org/wiki/Eesti#Ajalugu) is better.
