### ISSUE TITLE
portuguese-brazilian not being detected by vscode after being installed.

### ISSUE THREAD

**Issue by SHJordan** [streetsidesoftware/vscode-cspell-dict-extensions#21]
https://github.com/Jason3S/vscode-cspell-dict-extensions/tree/master/extensions/portuguese-Brazilian it is not showing as installed although it is.
![image](https://user-images.githubusercontent.com/884602/62980044-d1741f00-bdfb-11e9-82ec-d6b4602736da.png)

Hopefully this screenshot helps.

**Comment by Jason3S** [comment]
What happens when you restart VS Code? Make sure it doesn't leave behind any "Code Helper" processes.

**Comment by zomars** [comment]
I think this is related to #35 and #46

**Comment by Jason3S** [comment]
I believe this is fixed by #56
