### ISSUE TITLE
danish extension breaks cspell

### ISSUE THREAD

**Issue by Fragcys** [streetsidesoftware/vscode-cspell-dict-extensions#31]
When I enable the danish dictionary everything in the spell checker stops working for all enabled dictionaries, this does not happen if I try any of the other dict extensions, eg. I tried using the dutch dict and that does not stop cspell from working. I've tried with both "da" and "da-DK", am I maybe doing something wrong?

**Comment by Jason3S** [comment]
Thank you. I'll take a look.

**Comment by Jason3S** [comment]
I believe the issue has been fixed. Would you please update the extension and try again?

**Comment by Fragcys** [comment]
Works as intended now, thank you very much.
