### ISSUE TITLE
Add Indonesian language support with `id-ID` locale

### ISSUE THREAD

**Issue by rafiandria23** [streetsidesoftware/vscode-cspell-dict-extensions#318]
I would like to be able to add Indonesian language extension. Because I name variables in Indonesian in some cases, depending on requirements. I'm willing to create PR for this if needed.

**Comment by Jason3S** [comment]
@rafiandria23,

The place to start is by adding a dictionary here: [streetsidesoftware/cspell-dicts: Various cspell dictionaries](https://github.com/streetsidesoftware/cspell-dicts#how-to-create-a-new-dictionary).

Once that is done, it is easy to create an extension.

**Comment by rafiandria23** [comment]
@Jason3S noted, let me try to create PR in that. Thank you.
