### ISSUE TITLE
Russian dict problem

### ISSUE THREAD

**Issue by w1r3d7** [streetsidesoftware/vscode-cspell-dict-extensions#33]
Hello.
In our language we have _И & Й_ and this letters are different.
Plugin don't see _Й_ , convert that letter to _И_ and shows errors.

![in vscode](https://downloader.disk.yandex.ru/preview/1811d9e5fb944026f79fd838b9fa84475689e2b92c5598ebe5e3e229569e5ae9/5dc52fe3/iXlwUOvNcjP0dUxy97Bg-xIZ2HCUX4rqdWSo6OA5ILFdriWjTGjK5LKxEizAJyAfe3mjbiFZUlrxA1psx2H-fw==?uid=0&filename=2019-11-08_08-05-20.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=41708847&size=2048x2048)

**Comment by Jason3S** [comment]
@w1r3d7 what was the issue?
