### ISSUE TITLE
Couldn't use `yo cspell-dict-extensions` because of this issue

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [streetsidesoftware/vscode-cspell-dict-extensions#331]
![Screen Shot 2022-07-24 at 22 11 00](https://user-images.githubusercontent.com/24838274/180662312-830f02d7-fa0d-4a0c-a1fc-cc0843461c35.png)

and when I run `yo doctor I have this problem`

![Screen Shot 2022-07-24 at 22 08 04](https://user-images.githubusercontent.com/24838274/180662235-84283853-d6f3-4e88-99d5-845e1bc0fdfe.png)

I updated node and done some solutions on the internet without solving the problem.

**Comment by Jason3S** [comment]
@WatheqAlshowaiter,

Did you follow the setup instructions? [Install Yeoman](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/blob/main/CONTRIBUTING.md#install-yeoman).

**Install Yeoman Generator**
```sh
npm install
npm install -g yo
cd generator-cspell-dicts-extensions
npm install
npm link
cd ..
```

**Comment by WatheqAlshowaiter** [comment]
@Jason3S 
Yeah, I followd the instruction, but it seams I need to download the main repo. 
I have used Yarn and it makes a new issue.

thanks..

**Comment by Jason3S** [comment]
@WatheqAlshowaiter,

Yes, you need to fork this repo to make it work.
