### ISSUE TITLE
Can't add Arabic Hunspell compatible dictionarry 

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [streetsidesoftware/vscode-cspell-dict-extensions#335]
like how it is shown in the screanshot below.. 

![Screen Shot 2022-07-25 at 09 00 23](https://user-images.githubusercontent.com/24838274/180736198-0b8a3661-b74b-4a6a-b789-d445f4387265.png)

How can I add the dictionary manually to the extention?

**Comment by Jason3S** [comment]
@WatheqAlshowaiter,

A dictionary does not yet exist. See: https://github.com/streetsidesoftware/cspell-dicts/issues/941

**Comment by WatheqAlshowaiter** [comment]
thank you @Jason3S for reply.

I have two dictionaries, one is Hunspell compatible and the other is just a txt wordlist. How can I convert any of them to an extension dictionary? could you give me a hint?

**Comment by Jason3S** [comment]
@WatheqAlshowaiter,

The first step is to build a CSpell compatible dictionary. Once that has been done and published, it is generally an easy step to build an extension.
