### ISSUE TITLE
Arabic Extension is not working,

### ISSUE THREAD

**Issue by Jason3S** [streetsidesoftware/vscode-cspell-dict-extensions#340]
I tried to enable the Arabic Extension, but it's not working,
 - I install both the original code spell extension and the Arabic version 
- I click `f1` then `Show Spell Checker Configuration Info` then `I select the Arabic Language tab` 
- I make sure the settings and put `"cSpell.language": "en,ar"` into it  

But the Arabic checking not working, only the English is working.

_Originally posted by @AhmedElTabarani in https://github.com/streetsidesoftware/cspell-dicts/issues/941#issuecomment-1198592585_

**Comment by Jason3S** [comment]
@AhmedElTabarani,

Please open a file containing Arabic.

Click: 
<img width="74" alt="image" src="https://user-images.githubusercontent.com/3740137/181631518-9b1a37d7-8ef9-4db5-a562-50bb30de899c.png">

What do you see on this tab?:

<img width="751" alt="image" src="https://user-images.githubusercontent.com/3740137/181631349-131a0f4a-60f7-4a75-b320-8c4deb86fc89.png">

**Comment by AhmedElTabarani** [comment]
it is the same in your image, The Arabic and English are marked in both `User` and `WorkSpace`

**Comment by Jason3S** [comment]
Please make sure Arabic isn't blocked in the `cSpell.ignoreRegExpList`.

<img width="962" alt="image" src="https://user-images.githubusercontent.com/3740137/181634116-92986d27-daac-4bca-84a8-e4aac46b292e.png">

This is what I see when editing an Arabic file:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/3740137/181634389-3009a55b-47fe-4f37-86ff-837c5fde49ce.png">

**Comment by AhmedElTabarani** [comment]
Oh, I remember now, I block it since this issue https://github.com/streetsidesoftware/vscode-spell-checker/issues/1665, Sorry  😅
