### ISSUE TITLE
Reinstallation always required

### ISSUE THREAD

**Issue by Serhioromano** [streetsidesoftware/vscode-cspell-dict-extensions#35]
After some time I Russian checked in settings but it is marked with not available in UI. Only after deleting extension and install again it starts to work again.

![2020-01-10_13-44-13](https://user-images.githubusercontent.com/650741/72134909-60876200-33af-11ea-805b-bb0adaf52d61.png)

**Comment by grandsilence** [comment]
It's not extension issue. I'm using [chocolatey](https://chocolatey.org/) package manager and [Choco Cleaner](https://chocolatey.org/packages/choco-cleaner) script. 
**After running Choco Cleaner it breaks again.**

# Solution
* Reinstall extension every time after Choco Cleaner run

**Comment by zomars** [comment]
I'm not using a package manager. I think this is related to #46 

![image](https://user-images.githubusercontent.com/3504472/90665052-c15dff00-e208-11ea-8e73-a75837fc1b93.png)

**Comment by Jason3S** [comment]
@Serhioromano I have updated the extension. I hope the fix works for you. The issue seems to be machine and time dependent, which is why it might work on my machine but not yours.

**Comment by Jason3S** [comment]
I believe this is fixed by #56

**Comment by Serhioromano** [comment]
Perfect.
