### ISSUE TITLE
Is it possible to use alternatives for üöä

### ISSUE THREAD

**Issue by Lackmann1994** [streetsidesoftware/vscode-cspell-dict-extensions#408]
I have an existing project that uses german words for variables names.
A variable that for example describes a door is called tuer
Since the developer avoided to use üöä for variable names

In the long run i am planning to refactor the german variables to english names anyways 
but for a quick spell check i would like to allow words like tuer automatically as correct.

Is it possible to use alternatives for üöä like ue oe ae

**Comment by Jason3S** [comment]
@Lackmann1994,

I have updated the German dictionary to allow mapping alternate spellings of vowels with Umlauts.
Related to:
https://github.com/streetsidesoftware/cspell-dicts/pull/1500

Note: it is not a perfect solution. But it should help.
