### ISSUE TITLE
Publish extensions to open-vsx

### ISSUE THREAD

**Issue by orblazer** [streetsidesoftware/vscode-cspell-dict-extensions#41]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the _French - Code Spell Checker_ extension on the [open-vsx.org](https://open-vsx.org/) market to us doesn't need to works with the Microsoft marketplace as is unclear if it's legal to use it on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional info:

- This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

**Comment by dmaes** [comment]
+1 for this (I would like *Dutch*)

Seeing that [streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker) is already on [open-vsx.org](https://open-vsx.org) , I hope to see the language extensions soon

**Comment by bonkboykz** [comment]
Thanks for the work! +1 for the Russian spell checker

**Comment by Jason3S** [comment]
@dmaes and @orblazer I have published all the language extensions to Open-vsx.
