### ISSUE TITLE
I had to use `da` to activate the Danish dictionary

### ISSUE THREAD

**Issue by davidolrik** [streetsidesoftware/vscode-cspell-dict-extensions#44]
In the docs, and in the code of the extension, it says to use `dk` to activate the danish dictionary.

This did not work for me, but using `da` to activate the Danish dictionary did work.

**Comment by Jason3S** [comment]
`da` is correct. I'll look at the docs.

**Comment by Jason3S** [comment]
Fixed: [streetsidesoftware.code-spell-checker-danish](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-danish)
