### ISSUE TITLE
Extension has left vscode slow

### ISSUE THREAD

**Issue by WorkAttackDev** [streetsidesoftware/vscode-cspell-dict-extensions#555]
Type: <b>Bug</b>

Extension has left vscode slow

Extension version: 1.0.4
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.92GB (4.08GB free)|
|Process Argv|--crash-reporter-id 7b110de2-fe81-4988-a2e6-46c35074961a|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Jason3S** [comment]
@WorkAttackDev,

I believe the extension updated yesterday. Sometimes when VS Code updates an extension, it doesn't manage to fully stop the existing process.

Fix:
- fully quit VS Code.
- force quit any `Code Helper` processes that are still running.
- start up VS Code
