### ISSUE TITLE
Adding other languages

### ISSUE THREAD

**Issue by JakovGlavac** [streetsidesoftware/vscode-cspell-dict-extensions#61]
Hi, 
I'm wondering if there is a way to add support for other languages and if yes then, is there a way I could contribute?

**Comment by Jason3S** [comment]
@JakovGlavac,

Yes there is and please do. The place to start is [streetsidesoftware/cspell-dicts: Various cspell dictionaries](https://github.com/streetsidesoftware/cspell-dicts)

Once a dictionary is created, it is easy enough to add an extension.
