### ISSUE TITLE
Code Spell Checker-Swedish

### ISSUE THREAD

**Issue by MalinStal** [streetsidesoftware/vscode-cspell-dict-extensions#636]
have a problem with all words in Swedish being underlined as misspelled even though they are spelled correctly. If I mark those words, there are no Swedish alternative words to correct. which means that the Swedish version does not work.

**Comment by Jason3S** [comment]
@MalinStal,

I have to guess at with might be happening. There isn't much information here.

Did you enable the dictionary?
<img width="415" alt="image" src="https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/3740137/bcf0cee4-3235-453b-a3fc-0fa1f5d2b1d9">

A simple check is to add `cspell:locale sv` to the top of a file. If the `~~~` go away, then that is the issue.

**Comment by MalinStal** [comment]
Tanks now it works! 🤩

Den ons 10 maj 2023 14:29Jason Dent ***@***.***> skrev:
