### ISSUE TITLE
Does "Swiss German Code Spell Checker" extension work?

### ISSUE THREAD

**Issue by MSchmidke** [streetsidesoftware/vscode-cspell-dict-extensions#683]
Hi,

I've tried code-spell-checker-german extension, which works as expected, as well as code-spell-checker-swiss-german, which does not seem to work. Tried several variants of "de-ch", "de_ch", "de-CH" and so on in cspell settings, none of them were successful.

Meaning the same word, let it be "Farbe", is marked as wrong in any setting with swiss-german module, while it isn't marked with german module. CSpell Command Line finds them in both dictionaries:
```
marcus@Lenovo-2022:~$ cspell trace --only-found Farbe
Word  F Dictionary           Dictionary Location
Farbe * de-ch                node_modules/@cspell/dict-de-ch/de_CH.trie.gz
Farbe * de-de                node_modules/@cspell/dict-de-de/de_DE.trie.gz
```

Unfortunately, I do not have any experiences in developing VSCode extension, so I was unable to debug the code.

Am I doing something wrong, or could there be a bug in the extension? I've seen the "extension.ts" files are different in large parts, but since I do not understand what's happening, I cannot figure out if that's the problem.

Regards

Marcus.

**Comment by Jason3S** [comment]
@MSchmidke,

An easy way ensure that it is enabled, add the following to the document with issues:

```
cspell:locale de-ch
```

If the spelling issues go away, it means that the `de-ch` locale has not been enabled.

There are a few ways to enable `de-ch`:

## Using Settings
Using VS Code Settings:
![image](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/3740137/cb715e4a-1c6d-4952-8cef-93bfa1dcfd2c)

## Using a config file

Add a `cspell.config.yaml` file to your project:

```yaml
language: en,de-ch
```

## Run a command

`F1` `enable swiss`
![image](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/3740137/1f2af153-5a16-4943-8c35-3dce86b9c9f8)

**Comment by MSchmidke** [comment]
> add the following to the document with issues:

Ah! This is a good way to test, thank you! Will try it immediately.

Setting it to "en_US", the american words are fine.

![image](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/4288369/ee2ff40e-7c1b-48b7-9dee-befd819a89ea)

When setting it do en-gb, the british word Colour is also fine.

![image](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/4288369/255a45b3-80f1-4678-970b-55d5d2615c84)
Setting it to de-de, the German words like "Farbe", "britisch" and "Straßenbahn" are fine:

![image](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/4288369/a0e2f027-060b-4eaf-b6f1-1f1239c21cad)

Setting it to de-ch, nothing is fine:
![image](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/4288369/b8266f44-3312-46f8-9237-5c8be5e0ea2c)

And I claim having properly installed the extension:
![image](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/4288369/1df2ff6c-f48b-49f9-9c6c-fd47192d2051)

**Comment by Jason3S** [comment]
@MSchmidke,

Thank you for the excellent example.

This is what I see:
<img width="302" alt="image" src="https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/3740137/bd79a10a-6450-48f9-a2f9-de0ec767910c">


This only thing I can think of is to forcibly remove the extension and re-install. Sometimes vscode fails to install the full extension.

```
rm ~/.vscode/extensions/streetsidesoftware.code-spell-checker-swiss-german-1.1.1
```

**Comment by MSchmidke** [comment]
Oh no!

In the repo I was using for my experiments, someone already registered a "de-ch.txt" dictionaryDefinition ... I only would have had to scroll up in the cspell.json to see it.

But thank you very much for your reply - clarifying that the error is on my side helped a lot!
