### ISSUE TITLE
[BUG] PT_BR isn't working at all

### ISSUE THREAD

**Issue by mattpsvreis** [streetsidesoftware/vscode-cspell-dict-extensions#735]
It just doesn't work. I have the extension installed and it refuses to work, not recognizing any PT_BR words, therefore tagging them as unknown.

![image](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/79459754/2ee5c9e5-079f-489b-a00a-43978524d433)
![image](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/79459754/c1866a06-355e-48cd-81c3-8641fd53f714)
![image](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/79459754/8e098672-23b8-475e-8f94-5e9e080ea1bb)
![image](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/79459754/c5056a2d-07d4-4ce4-9576-023d473c288f)

I don't know what else to do to make it work.

**Comment by Jason3S** [comment]
@mattpsvreis,

The easiest test is to add a cspell directive to set the locale:

```
cspell:locale pt-br

selecionado
```

If that works, then it is an issue with the settings.

**Comment by mattpsvreis** [comment]
Sorry it took me a moment to come back to this.

Turns out enabling it at the USER level isn't enough. You also need to enable it at WORKSPACE level.

Might want to consider fixing this! USER level should overwrite WORKSPACE level imo!

**Comment by Jason3S** [comment]
@mattpsvreis,

This is an issue with VS Code. Not much an extension can do. See: [Visual Studio Code User and Workspace Settings](https://code.visualstudio.com/docs/getstarted/settings)
