### ISSUE TITLE
As a user, when I install UK (i.e. British) extension, I want US words to be deprioritised so they're correct BUG

### ISSUE THREAD

**Issue by ldexterldesign** [streetsidesoftware/vscode-cspell-dict-extensions#797]
👋

Thanks for software

As title

Screenshot:
<img width="1840" alt="Screenshot 2023-11-28 at 20 43 14" src="https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/1715809/453234f9-77ef-400f-acdd-ab43c5d6b4b7">

# Steps to reproduce issue

Type "minimise" (i.e. correct British spelling)

Aside, "minimize" would be correct US spelling

# Unexpected behaviour

Highlight prompt to correct

# Expected behaviour

No highlight prompt to correct

If you're reading and:
- agree then please vote up (e.g. +1, like), or;
- disagree then please vote down (e.g. -1, dislike) - I'd love to know why?

Hope this helps

Regards

**Comment by Jason3S** [comment]
@ldexterldesign,

I think there are two issues going on here:
1. It is not obvious that British English needs to be enabled. 
2. Most US English words are acceptable in British English: [Oxford English `minimise`](https://www.oxfordlearnersdictionaries.com/definition/english/minimize?q=minimise) 

To [Manually Enable](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/blob/main/extensions/british-english/README.md#manual-settings) British English:

Go to VS Code settings, search for `spell language` and set it to `en-GB`:
<img width="764" alt="image" src="https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/3740137/1c2ab03c-fee6-47c2-a2c4-84849e5fa14a">

It is also possible to use the command palette: `F1` -> `enable British`

<img width="622" alt="image" src="https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/3740137/ad70692d-50cd-42ca-8c8c-5b4ea2123cb4">


There is also a setting to flag words you do not want:
<img width="959" alt="image" src="https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/3740137/1ea25d14-c439-42a0-9216-be6f88e88132">

**Comment by ldexterldesign** [comment]
👋 @Jason3S,

Thanks for quick reply

Admittedly I didn't read the extension README (I just expected it to work after installing and enabling the GB extension - and it could just be me - but I think the README could be improved...

Essentially, if the extension can't be good to go after install then I would put this - or something to the effect of what you illustrated above - right at the top of the README:
<img width="1840" alt="Screenshot 2023-11-29 at 18 50 45" src="https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/1715809/178c3929-b4ac-4e6d-805d-f46cd5d13712">

Hope this helps

Regards
