### ISSUE TITLE
Indonesian dictionary extension

### ISSUE THREAD

**Issue by afifvdin** [streetsidesoftware/vscode-cspell-dict-extensions#841]
Hi, I'm trying to create a new extension for the Indonesian dictionary. Have done the steps mentioned on [How to Create a New Extension](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/blob/main/CONTRIBUTING.md)

- Name: indonesian
- Friendly Name: Indonesian
- Display Name: Indonesian - Code Spell Checker
- Description: Indonesian dictionary extension for VS Code.
- Source: @cspell/dict-id-id
- Add Enable/Disable Commands: Yes
- Base Name for Commands: Indonesian
- Language Local: id-id
- Target Directory extensions/indonesian
- NPM Package Name: code-spell-checker-indonesian

But during the test it doesn't work (blue squiggly lines still appear). I've tried to check the Indonesian option on the workspace tab and user tab, but nothing is working. Is there a step I'm missing? thanks.

I'm using Node.js v20.11 on Ubuntu 22

**Comment by Jason3S** [comment]
@afifvdin,

The Indonesian language might not be enabled.

Quick check, in your document add the following: `cspell:locale id`

There should be a command that gets installed with the extension: `F1` - `Indonesian` should show it.

**Comment by afifvdin** [comment]
@Jason3S 

the command is there but still not working. maybe there's something missing in the package. i looked at [@cspell/dict-fr-fr](https://www.npmjs.com/package/@cspell/dict-fr-fr?activeTab=code) and [@cspell/dict-ar](https://www.npmjs.com/package/@cspell/dict-ar?activeTab=code) packages and there was .tree.gz file inside

**Comment by Jason3S** [comment]
Ooops. https://github.com/streetsidesoftware/cspell-dicts/pull/2930

**Comment by Jason3S** [comment]
@afifvdin,

It should be updated on https://www.npmjs.com/package/@cspell/dict-id-id

**Comment by afifvdin** [comment]
@Jason3S 
Thank you, it works now. will close this issue
