### ISSUE TITLE
Use of Medical Terms Dictionary Violates GPLv3.0

### ISSUE THREAD

**Issue by Kurt-von-Laven** [streetsidesoftware/vscode-cspell-dict-extensions#87]
The [medical terms extension](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/tree/master/extensions/medical-terms) [cites](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/tree/master/extensions/medical-terms#list-of-english-medical-terms) a [GPLv3.0](https://github.com/glutanimate/wordlist-medicalterms-en/blob/master/LICENSE) project as the source of its dictionary yet [relicenses it MIT](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/tree/master/extensions/medical-terms/LICENSE). See [this just fixed issue](https://github.com/streetsidesoftware/cspell-dicts/issues/440) for further details.

**Comment by Jason3S** [comment]
Fixed by #91
