### ISSUE TITLE
Document how to add words to dictionaries

### ISSUE THREAD

**Issue by AndiDog** [streetsidesoftware/vscode-cspell-dict-extensions#900]
Contributors should be able to find in [CONTRIBUTING.md](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/blob/main/CONTRIBUTING.md) how common words per language can be added. If that's not easy, people will keep having to add lots of words to their local dictionary which does not help other users. I looked around for a few minutes but could not easily find this information.

**Comment by Jason3S** [comment]
@AndiDog,

You make a good point. Would you be open to making a PR that points would be contributors to [streetsidesoftware/cspell-dicts: Various cspell dictionaries](https://github.com/streetsidesoftware/cspell-dicts)? All the extensions in this repo are based upon the dictionaries found in `cspell-dicts`.

I must admit, the instructions on how to add words is not ideal. Most dictionaries have a `src/additional_words.txt` file.
