### ISSUE TITLE
Latin extension

### ISSUE THREAD

**Issue by juliaanvaneijndt** [streetsidesoftware/vscode-cspell-dict-extensions#909]
Hi,
I see the [Latin dictionary](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/la) exists but not the corresponding extension: it would be great to have it! Thanks for all the great work.

**Comment by Jason3S** [comment]
@juliaanvaneijndt,

Thank you for the reminder. Please try it out: [Latin - Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-latin)
