### ISSUE TITLE
THE EXTENSION DOES NOT ALLOW YOU TO USE THE LETTER S WITHIN THE PROGRAM.

### ISSUE THREAD

**Issue by karinaklima** [streetsidesoftware/vscode-cspell-dict-extensions#950]
Type: <b>Bug</b>

THE EXTENSION DOES NOT ALLOW YOU TO USE THE LETTER S WITHIN THE PROGRAM. I WOULD LIKE THE PROBLEM TO BE SOLVED.

Extension version: 2.2.1
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (1.96GB free)|
|Process Argv|--crash-reporter-id 266ae236-5894-41b4-98a4-61f32329c626|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
chatpanelc:31048052
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31049070
a69g1124:31058053
pythonprt:31056678
dwnewjupytercf:31046870
fa862199:31048878

```

</details>

**Comment by karinaklima** [comment]
MS-CEINTL.vscode-language-pack-pt-BR

**Comment by karinaklima** [comment]
THE EXTENSION HAS BEEN UNINSTALLED AND THE PROBLEM CONTINUES.

**Comment by Jason3S** [comment]
@karinaklima,

It is clear you are frustrated.

Are you sure that you had installed "Brazilian Portuguese - Code Spell Checker"?
<img width="893" alt="image" src="https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/3740137/956b2661-8159-4165-b468-b4b5019d7efe">

This extension is unrelated to: `MS-CEINTL.vscode-language-pack-pt-BR`.

Kind regards,
Jason

**Comment by karinaklima** [comment]
I've already removed this extension and it still doesn't work, how can I solve it?

**Comment by Jason3S** [comment]
@karinaklima,

I have the idea that something else is going on that is unrelated to this extension.

If you want to make sure the extension is fully deleted, you can delete the extension files. See [Where are Extension Installed](https://code.visualstudio.com/docs/editor/extension-marketplace#_where-are-extensions-installed).

1. Quit VS Code.
2. Delete all directories starting with `streetsidesoftware`.
![image](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/assets/3740137/4ddc1821-73c3-4ef5-89ad-e0f27cd6e9c3)
3. Restart VS Code.

I hope this helps. If the problem continues, then it has nothing to do with the spell checker extension.

Kind regards,
Jason
