### ISSUE TITLE
Error: Failed to read config file "/Users/…/.vscode/extensions/streetsidesof tware.code-spell-checker-spanish-2.3.4/@cspell/dict- es-es/cspell-ext.json"

### ISSUE THREAD

**Issue by moitorrijos** [streetsidesoftware/vscode-cspell-dict-extensions#966]
Hi, I must've accidentally deleted something when doing _npkill_ maintenance in my machine.

Everytime I open a project in VSCode I get the following message and most of the words are not recognized and are marked as error with blue skwiglys.

`"/Users/…/.vscode/extensions/streetsidesof tware.code-spell-checker-spanish-2.3.4/@cspell/dict- es-es/cspell-ext.json" imported by "/Users/…/.vscode/extensions/streetsidesof tware.code-spell-checker-spanish-2.3.4/cspell- ext.json"`

![CleanShot 2024-06-19 at 09 44 51@2x](https://github.com/streetsidesoftware/cspell-dicts/assets/546005/1e3982ea-492e-4934-8b10-4d7a85af3482)

I tried installing cspell and running `cspell link list` and the list appears empty. Is there a way I can download or generate the missing file?

**Comment by Jason3S** [comment]
@moitorrijos,

That must be frustrating.

The easiest fix is to just delete the folders: `~/.vscode/extensions/streetsidesoftware.code-spell-checker-spanish*` and re-install the extension.

Trying to install the dictionary separately and linking it isn't really advised.

**Comment by Darkzarich** [comment]
Had a similar issue here: https://github.com/streetsidesoftware/vscode-spell-checker/issues/5312
It happened after `node_modules` disappeared from the extension directory, I might have deleted it somehow. 
Simple extension reinstall did not help in this case.
