### ISSUE TITLE
Latin dictionary fails to understand Lorem ipsum snippets

### ISSUE THREAD

**Issue by gforcada** [streetsidesoftware/vscode-cspell-dict-extensions#975]
Hi,

thanks a lot for the VS Code extension and its dictionaries, it has been a huge help for us ✨ 

I noticed though, that with the Latin dictionary enabled, the famous `Lorem Ipsum` text is marked as that there are typos.

It would be great that the Latin dictionary supports `Lorem Ipsum` as I'm expecting lots of developers that use VS Code to have those words in plenty of templates and code 🙃 

To get some text to test see https://lipsum.com/

I could try my best to contribute if I'm pointed how to do so 😊

**Comment by gforcada** [comment]
I noticed that the dictionaries come from `cspell` and that there is a [`lorem-ipsum` dictionary](https://github.com/streetsidesoftware/cspell-dicts/tree/6d49df9d167cdb09a9bbc70f916379e6cc2837b5/dictionaries/lorem-ipsum) 🎉 

Unfortunately, I don't see it as an extension in [VS Code marketplace](https://marketplace.visualstudio.com/publishers/streetsidesoftware) 🤷🏾 

It is my poor search skills, or it is not released there? Could that be possible? 🍀

**Comment by Jason3S** [comment]
@gforcada,

`lorem-ipsum` comes with the extension, but needs to be enabled:

- https://github.com/streetsidesoftware/vscode-spell-checker/issues/2688
- https://github.com/streetsidesoftware/cspell/issues/1999
- https://github.com/streetsidesoftware/vscode-spell-checker/issues/2423
- https://github.com/streetsidesoftware/vscode-spell-checker/issues/226

The above issues should contain enough information. If you need more help, just ask.

**Comment by gforcada** [comment]
Thanks! Sorry that I did not search through the issues before opening a new one 🙏🏾
